'C:\Users\kunil\AppData\Roaming\JetBrains\Rider2022.3\scratches\FL_05.puml
@startuml
autonumber "<b>[00]"
skinparam maxMessageSize 200
hide unlinked

participant "UFO" as UFO
participant "SmartData" as SmartData
participant "Intellinx (Antifraud System)" as Intellinx
box "Kafka"
    participant "<color:red>**[NEW]**</color> ufo-queuing-forceLogoutBlock" as          KafkaUFOBlock
    participant "<color:red>**[NEW]**</color> ufo-queuing-forceLogoutUnblock" as        KafkaUFOUnblock
    participant "<color:red>**[NEW]**</color> intellinx-queuing-updateStopList" as      KafkaIntellinx
    participant "<color:red>**[NEW]**</color> smartdata-events-forceLogout" as          KafkaSmartData
    participant "<color:red>**[NEW]**</color> netflix-events-forceLogout" as            KafkaNetflix
    participant "<color:red>**[NEW]**</color> snitchOff_queuing_blackListChecks" as     KafkaSnitchOff
end box
participant "MS Checker" as             Checker
participant "Snitch Back" as            Snitch
participant "Netflix Conductor" as      Netflix
participant "SMS-Gate" as               smsgate
actor "Bank Client" as                  client
participant "Ocelot Api Gateway" as     ocelot
participant "myc-auth-server api" as    api

title Обновление кэша блокируемых пользователей в Ocelot OB
==Временное решение==
loop
    ocelot -> api: GET myc-auth-server/v1/ClientBlock/GetLastHourBlocks
    ocelot <-- api: Идентификаторы клиентов, заблокированных за последний час
    ocelot -> ocelot: Сохранить список идентификаторов (кэшируем ClientId)
end
==Целевое решение==
rnote right ocelot
В целевом решении не требуется вычитывать кэш Ocelot.
Ходим в snitch-oc напрямую по API
end note
legend right
    | Цвет      | Назначение  | Абривиатура |
    |<#Red>     | Добавление  | [ADD]       |
    |<#magenta> | Изменение   | [MOD]       |
    |<#gray>    | Удаление    | [DEL]       |
endlegend
@enduml